version: '3.8'

services:
  ddns:
    image: jeidnx/fritzbox-cloudflare-ddns:latest
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - auth_email=      # The email used to login 'https://dash.cloudflare.com'
      - auth_method=     # Set to "global" for Global API Key or "token" for Scoped API Token
      - auth_key=        # Your API Token or Global API Key
      - zone_identifier= # Can be found in the "Overview" tab of your domain
      - record_names=    # Which records you want to be updated, seperated by spacesc
      - discorduri=      # Discord Hook URI
